jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false
unclassified:
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultSuffix: "@csw.l-3com.com"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpHost: "nemesis"
      smtpPassword: ""
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  location:
    adminAddress: "me@foobar.com"
    url: "http://localhost:8080/"
  metricsAccessKey:
    accessKeys:
    - canHealthCheck: true
      canMetrics: true
      canPing: true
      canThreadDump: false
      description: "metrics"
      key: "publicHealthCheckAccessKey"
      origins: "*"

jobs:
  - script: >
      job('Job_DSL_Seed') {
        steps {
          jobDsl {
            removedJobAction('DELETE')
            scriptText(
            '''
             [ "foss", "clf" ].each {
               def projectName = it
               organizationFolder(projectName) {
                 description("This contains branch source jobs for Bitbucket project " + projectName)
                 displayName(projectName)

                 organizations {
                     bitbucket {
                       repoOwner(projectName)
                       credentialsId('ROuser')
                       traits {
                         sourceRegexFilter {
                           // A Java regular expression to restrict the project names.
                           regex('.*')
                         }
                       }
                     }
                   }
                   orphanedItemStrategy {
                       discardOldItems {
                           daysToKeep(10)
                           numToKeep(10)
                       }
                   } 
                 }
             }
             '''.stripIndent())
          }
        }
      }
