jobs:
  - script: >
      job('Job_DSL_Seed') {
        steps {
          jobDsl {
            removedJobAction('DELETE')
            scriptText(
            '''
             [ "foss", "clf" ].each {
               def projectName = it
               organizationFolder(projectName) {
                 description("This contains branch source jobs for Bitbucket project " + projectName)
                 displayName(projectName)

                 organizations {
                     bitbucket {
                       repoOwner(projectName)
                       credentialsId('ROuser')
                       traits {
                         sourceRegexFilter {
                           // A Java regular expression to restrict the project names.
                           regex('.*')
                         }
                       }
                     }
                   }
                   orphanedItemStrategy {
                       discardOldItems {
                           daysToKeep(10)
                           numToKeep(10)
                       }
                   } 
                 }
             }
             '''.stripIndent())
          }
        }
      }
