jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Agent/Configure:anonymous"
        - "Agent/Connect:anonymous"
        - "Agent/Create:anonymous"
        - "Overall/Administer:admin"
        - "Overall/Read:anonymous"
        - "Overall/Read:authenticated"
        - "Overall/SystemRead:anonymous"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false
